version: '3.5'

volumes:
  postgres_user_volume:

services:
  postgres:
    image: postgres:14-alpine
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
    ports:
      - "5434:5432"
    networks:
      - cart-network

  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    restart: on-failure
    env_file:
      - .env
    networks:
      - cart-network

  user-service:
    restart: always
    build: .
    depends_on:
      - postgres
    ports:
      - "${GRPC_PORT:-5003}:${GRPC_PORT:-5003}"
      - "${HTTP_PORT:-8082}:${HTTP_PORT:-8082}"
      - "${SWAGGER_PORT:-8092}:${SWAGGER_PORT:-8092}"
    networks:
      - cart-network

networks:
  cart-network: